# Sports Car Project - Explore with SQL
In this notebook I will use SQL queries to explore the data. I will import the relelvant modules (pandas, sqlite3), create a connection to the database (`sports_cars.db`) which has an empty table schema already set up. I will then import the data from the `sports_car_clean.csv`. \
The aim of this notebook is to use SQL to:
- View all of the data
- Look at total number of entries, and any null values in each column
- Descriptive statistics for numeric columns
- Descriptive statistics grouped by categories (e.g. grouped by year, engine type and make)
- Look at top 5 cars (i.e. most powerful, most expensive, fastest acceleration)

In [6]:
import sqlite3
import pandas as pd


conn = sqlite3.connect("sports_cars.db")

pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type = 'table';
""", conn)



df = pd.read_csv("sports_car_clean.csv")

df.to_sql(
    "cars",
    conn,
    if_exists="replace",
    index=False
)


pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
### View the data

In [7]:
pd.read_sql("""
SELECT *
FROM cars;
""", conn)

,make,model,year,numeric_engine_size,engine_type,horsepower,flag_hp_estimate,torque_lb,flag_torque_estimate,zero_to_sixty,flag_zero_to_sixty_estimate,price_usd,price_gbp
0,Porsche,911,2022,3.00,Combustion,379,0,331.00,0.00,4.00,0,"101,200.00","78,936.00"
1,Lamborghini,Huracan,2021,5.20,Combustion,630,0,443.00,0.00,2.80,0,"274,390.00","214,024.20"
2,Ferrari,488 GTB,2022,3.90,Combustion,661,0,561.00,0.00,3.00,0,"333,750.00","260,325.00"
3,Audi,R8,2022,5.20,Combustion,562,0,406.00,0.00,3.20,0,"142,700.00","111,306.00"
4,McLaren,720S,2021,4.00,Combustion,710,0,568.00,0.00,2.70,0,"298,000.00","232,440.00"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,Mercedes-Benz,SLS AMG,2021,6.30,Combustion,622,0,468.00,0.00,3.60,0,"254,500.00","198,510.00"
632,Ford,Mustang,2021,2.30,Combustion,310,0,350.00,0.00,5.30,0,"27,205.00","21,219.90"
633,Koenigsegg,Jesko,2022,5.00,Combustion,1280,0,"1,106.00",0.00,2.50,0,"3,000,000.00","2,340,000.00"
634,Lotus,Evija,2021,NaN,Electric,1972,0,"1,254.00",0.00,2.00,0,"2,000,000.00","1,560,000.00"
635,Rimac,Nevera,2021,NaN,Electric,1888,0,"1,696.00",0.00,1.85,0,"2,400,000.00","1,872,000.00"

In [ ]:
## looking at total number of values and null values in data

In [15]:
pd.read_sql("""
SELECT COUNT(*) AS total_count,
SUM(numeric_engine_size IS NULL) AS null_size,
SUM(engine_type IS NULL) AS null_type,
SUM(horsepower IS NULL) AS null_hp, 
SUM(torque_lb IS NULL) AS null_torque, 
SUM(zero_to_sixty IS NULL) AS null_accel, 
SUM(price_gbp IS NULL) AS null_price
FROM cars;
""", conn)

,total_count,null_size,null_type,null_hp,null_torque,null_accel,null_price
0,636,48,0,0,4,0,0

In [ ]:
### Descriptive statistics (average, min, max) for each numeric category

In [22]:
# engine size 
pd.read_sql("""
SELECT AVG(numeric_engine_size) AS avg_size,
MIN(numeric_engine_size) AS min_size,
MAX(numeric_engine_size) AS max_size
FROM cars;
""", conn)

   avg_size  min_size  max_size
0      4.45      1.50      8.40

In [23]:
# horsepower 
pd.read_sql("""
SELECT AVG(horsepower) AS avg_hp,
MIN(horsepower) AS min_hp,
MAX(horsepower) AS max_hp
FROM cars;
""", conn)

   avg_hp  min_hp  max_hp
0  626.61     181    2000

In [24]:
# torque 
pd.read_sql("""
SELECT AVG(torque_lb) AS avg_torque,
MIN(torque_lb) AS min_torque,
MAX(torque_lb) AS max_torque
FROM cars;
""", conn)

   avg_torque  min_torque  max_torque
0      548.23      151.00    1,732.00

In [25]:
# 0-60 accel 
pd.read_sql("""
SELECT AVG(zero_to_sixty) AS avg_zero_sixty,
MIN(zero_to_sixty) AS min_zero_sixty,
MAX(zero_to_sixty) AS max_zero_sixty
FROM cars;
""", conn)

   avg_zero_sixty  min_zero_sixty  max_zero_sixty
0            3.55            1.80            6.50

In [26]:
# price
 
pd.read_sql("""
SELECT AVG(price_gbp) AS avg_price,
MIN(price_gbp) AS min_price,
MAX(price_gbp) AS max_price
FROM cars;
""", conn)

   avg_price  min_price    max_price
0 298,114.76  19,500.00 4,056,000.00

In [ ]:
### Average grouped by Engine type

In [16]:
pd.read_sql(""" 
SELECT engine_type, 
AVG(horsepower) AS avg_hp, 
AVG(torque_lb) AS avg_torque,
AVG(zero_to_sixty) AS avg_zero_to_sixty,
AVG(price_gbp) AS avg_price
FROM cars
GROUP BY engine_type;
""", conn)

  engine_type   avg_hp  avg_torque  avg_zero_to_sixty  avg_price
0  Combustion   579.44      509.25               3.64 260,620.77
1    Electric 1,251.89    1,124.58               2.32 805,888.38
2      Hybrid   683.50      514.25               3.17 224,220.75

In [ ]:
### Average grouped by year

In [13]:
pd.read_sql(""" 
SELECT year, 
AVG(horsepower) AS avg_hp, 
AVG(torque_lb) AS avg_torque,
AVG(zero_to_sixty) AS avg_zero_to_sixty,
AVG(price_gbp) AS avg_price
FROM cars
GROUP BY year
ORDER by year;
""", conn)

   year      avg_hp  avg_torque  avg_zero_to_sixty      avg_price
0  1965  435.000000  440.000000           4.200000  780000.000000
1  2014  622.000000  468.000000           3.500000  214500.000000
2  2015  664.666667  548.777778           3.311111  584537.200000
3  2017  645.000000  600.000000           3.300000   94896.100000
4  2019  615.333333  533.666667           3.600000  346574.800000
5  2020  462.083333  386.166667           3.908333  255430.890000
6  2021  631.359420  550.685131           3.491681  302868.752522
7  2022  634.700405  560.575510           3.610202  288047.280000
8  2023  675.000000  579.000000           2.833333   84500.000000

In [ ]:
### Average grouped by make (only those with count of more than 10)

In [36]:
pd.read_sql(""" 
SELECT make, 
COUNT(*) AS make_count,
AVG(horsepower) AS avg_hp, 
AVG(torque_lb) AS avg_torque,
AVG(zero_to_sixty) AS avg_zero_to_sixty,
AVG(price_gbp) AS avg_price
FROM cars
GROUP BY make
HAVING make_count >= 10
ORDER BY make_count DESC;
""", conn)

,make,make_count,avg_hp,avg_torque,avg_zero_to_sixty,avg_price
0,Porsche,63,465.94,427.84,4.00,"108,933.81"
1,Audi,50,492.84,474.18,3.56,"71,155.89"
2,Mercedes-Benz,46,558.41,506.26,3.66,"126,421.98"
3,McLaren,43,622.35,481.88,2.99,"260,824.56"
4,Lamborghini,38,730.32,535.37,2.95,"392,790.98"
5,Dodge,37,701.46,639.38,3.61,"55,899.86"
6,Chevrolet,36,545.14,543.06,3.65,"42,515.42"
7,Aston Martin,33,607.03,565.45,3.49,"176,825.34"
8,BMW,29,465.79,426.52,3.89,"65,105.26"
9,Ferrari,28,700.54,553.89,3.07,"237,684.94"
10,Lotus,24,806.29,551.25,3.46,"541,676.04"
11,Nissan,21,360.00,287.86,4.74,"38,646.40"
12,Jaguar,20,409.10,376.70,4.63,"60,155.55"
13,Bentley,19,600.74,633.68,3.53,"169,884.00"
14,Tesla,15,"1,014.67",997.83,1.93,"118,977.04"
15,Maserati,15,471.53,395.00,4.49,"117,831.22"
16,Ford,15,526.93,463.67,3.87,"130,945.36"
17,Alfa Romeo,15,415.67,381.33,3.91,"58,187.74"
18,Pagani,10,757.20,745.20,2.80,"2,207,400.00"
19,Mercedes-AMG,10,571.00,540.80,3.50,"119,964.00"
20,Koenigsegg,10,"1,342.20","1,069.60",2.46,"2,262,000.00"
21,Bugatti,10,"1,509.30","1,180.00",2.39,"2,792,010.00"

In [10]:
# top 5 fastest cars (0-60)

pd.read_sql(""" 
SELECT make, 
model,
zero_to_sixty 
FROM cars
ORDER BY zero_to_sixty ASC
LIMIT 5;
""", conn)

    make   model  zero_to_sixty
0  Rimac   C_Two           1.80
1  Rimac   C_Two           1.80
2  Rimac  Nevera           1.85
3  Rimac   C_Two           1.85
4  Rimac  Nevera           1.85

In [11]:
# top 5 most powerful cars (hp)

pd.read_sql(""" 
SELECT make, model,
horsepower 
FROM cars
ORDER BY horsepower DESC
LIMIT 5;
""", conn)

    make  model  horsepower
0  Lotus  Evija        2000
1  Lotus  Evija        1973
2  Lotus  Evija        1973
3  Lotus  Evija        1973
4  Lotus  Evija        1972

In [12]:
# top 5 most expensive cars 
pd.read_sql(""" 
SELECT make, model,
price_gbp 
FROM cars
ORDER BY price_gbp DESC
LIMIT 5;
""", conn)

          make                    model    price_gbp
0      Bugatti  Chiron Super Sport 300+ 4,056,000.00
1      Bugatti  Chiron Super Sport 300+ 4,056,000.00
2      Bugatti                   Chiron 3,042,000.00
3  Lamborghini                     Sián 2,808,000.00
4      Bugatti         Chiron Pur Sport 2,807,220.00